### ISSUE TITLE
Optimize Prometheus metrics cost (MetricSampleCount)

### ISSUE THREAD

**Issue by pinskera** [aws-samples/terraform-workloads-ready-eks-accelerator#6]
**Is your feature request related to a problem? Please describe.**
The current setup for Prometheus metrics may lead to increased costs due to the MetricSampleCount metric. It would be beneficial to explore optimization strategies to reduce these costs.

**Describe the solution you'd like**
I would like to see optimizations implemented in the Prometheus configuration or related components to reduce the volume of MetricSampleCount metrics generated, thereby lowering associated costs.

**Describe alternatives you've considered**
Exploring different configurations or aggregation techniques within Prometheus to minimize the number of MetricSampleCount metrics generated.

**Additional context**
Optimizing Prometheus metrics can not only lead to cost savings but also improve the efficiency of monitoring and resource utilization within the cluster. This optimization aligns with best practices for managing cloud resources effectively.

**Comment by tsahiduek** [comment]
Solved by #7 .
Closing it.
