### ISSUE TITLE
Migrate AMP managed collector to use Cluster Access Management 

### ISSUE THREAD

**Issue by tsahiduek** [aws-samples/terraform-workloads-ready-eks-accelerator#8]
**Is your feature request related to a problem? Please describe.**
Currently the Managed Collector use `aws-auth` configmap for cluster authentication.
Following this recent [announcement](https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-managed-service-prometheus-collector-eks-access-management-controls/), it make sense to migrate the access control to the new [Amazon EKS access management controls ](https://docs.aws.amazon.com/eks/latest/userguide/access-entries.html).

Collector docs with the updated change is [here](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-collector-how-to.html#AMP-collector-create)

**Describe the solution you'd like**
Implement cluster access management for AMP Managed collector

**Describe alternatives you've considered**
Keep the current stat of using the `aws-auth` configMap

**Additional context**
N/A

**Comment by erezzarum** [comment]
AMP Scrapper will automatically create access entires when cluster authentication mechanism is set to API or API and ConfigMap (aws-auth).
Will update to remove configuration of aws-auth
